apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prozorro-eds.fullname" . }}-nginx-conf
  labels:
    {{- include "prozorro-eds.labels" . | nindent 4 }}
data:
  nginx.conf: |-

    server {
        listen 8000;
        server_name _;

        client_max_body_size 5M;
        access_log off;
        server_tokens off;

        root /usr/share/nginx/html;
        index index.html;
        set_real_ip_from 10.0.0.0/8;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;

        location / {
            try_files $uri $uri/ /index.html;
        }

        gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
        gzip on;
    }

